backend:
#  name: git-gateway
   name: github
   repo: NFTStackinfo/webly-landing
   branch: main

#publish_mode: editorial_workflow

media_folder: static/assets
public_folder: /assets

collections:
  # homepage
  - name: homepage-hero
    label: Homepage Hero
    folder: src/markdown/homepage-hero
    preview_path: /
    create: true
    editor:
      preview: false
    fields:
      - { name: title, label: Title }
      - { name: sectionHeading, label: Hero Heading }
      - { name: sectionText, label: Hero Text }
      - { name: sectionBtnText, label: Hero button text }

  # 404
  - name: not-found
    label: Not Found
    folder: src/markdown/not-found
    preview_path: /
    create: true
    editor:
      preview: false
    fields:
      - { name: title, label: Title }
      - { name: heroHeading, label: Hero heading }
      - { name: heroText, label: Hero text, widget: text }
      - { name: primaryBtn, label: Primary Button }
      - { name: secondaryBtn, label: Secondary Button }
      - { name: heroImg, label: Hero image, widget: image }
