backend:
#  name: git-gateway
   name: github
   repo: NFTStackinfo/webly-landing
   branch: main

#publish_mode: editorial_workflow

media_folder: static/assets
public_folder: /assets

collections:
  # homepage
  - name: homepage-hero-1
    label: Homepage Banner 1
    folder: src/markdown/homepage-hero-1
    preview_path: /
    create: true
    editor:
      preview: false
    fields:
      - { name: title, label: Title, widget: hidden }
      - { name: metaTitle, label: Meta Title }
      - { name: metaDescription, label: Meta Description, widget: text }
      - { name: heroHeading, label: Banner Heading }
      - { name: heroText, label: Banner Text }
      - { name: heroBtnPrimary, label: Banner button primary }
      - { name: heroBtnPrimaryUrl, label: Banner button primary url }
      - { name: heroBtnSecondary, label: Banner button secondary }
      - { name: heroBtnSecondaryUrl, label: Banner button secondary url }
      - { name: heroImg, label: Banner image, widget: image }
      - { name: calculatorTitle, label: Calculator Title }

  # 404
  - name: not-found
    label: Not Found
    folder: src/markdown/not-found
    preview_path: /
    create: true
    editor:
      preview: false
    fields:
      - { name: title, label: Title }
      - { name: heroHeading, label: Hero heading }
      - { name: heroText, label: Hero text, widget: text }
      - { name: primaryBtn, label: Primary Button }
      - { name: secondaryBtn, label: Secondary Button }
      - { name: heroImg, label: Hero image, widget: image }
